### ISSUE TITLE
Major versions of dependencies

### ISSUE THREAD

**Issue by billyb2** [rnestler/rust-torrent-search#43] opened 2021-03-09 18:31 UTC
How would you feel about always using the latest non-breaking version of all dependencies. For example, using every release of percent-encoding version 2 instead of one specific release, or the same with tokio 0.2

**Comment by rnestler** [comment] 2021-03-17 23:08
I like to have the `Cargo.lock` under version control to have reproducible builds. This is a best practice for Rust applications as described in https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries.

But I can run `cargo update` more often to get the latest non-breaking version of dependencies in the future.

**Comment by billyb2** [comment] 2021-03-18 16:16
Oh alright, thank you. I didn't know much about this.

**Comment by rnestler** [comment] 2021-06-07 13:56
Closing, since not really an issue.

**Closed by rnestler** 2021-06-07 13:56 UTC
